"""Chore: table minor fix

Revision ID: 00c2b101589b
Revises: 20686f04fcf2
Create Date: 2024-01-21 01:19:25.622332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00c2b101589b'
down_revision: Union[str, None] = '20686f04fcf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_rss_url'), ['rss_url'], unique=False)
        batch_op.create_unique_constraint('uix_item_rss_url_channel_id', ['rss_url', 'channel_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('uix_item_rss_url_channel_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_subscription_rss_url'))

    # ### end Alembic commands ###
