"""Initial migration

Revision ID: 360a12aa5280
Revises: 
Create Date: 2024-01-19 18:57:11.190190

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "360a12aa5280"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rss_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("channel_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_checked", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rss_url"),
    )
    op.create_index(op.f("ix_subscription_channel_id"), "subscription", ["channel_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_channel_id"), table_name="subscription")
    op.drop_table("subscription")
    # ### end Alembic commands ###
