"""table subscription renamed

Revision ID: 8769b1a84b3e
Revises: 00c2b101589b
Create Date: 2024-01-21 19:40:45.797511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8769b1a84b3e'
down_revision: Union[str, None] = '00c2b101589b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'channel_id', name='unique_item_url_channel_id')
    )
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_url'), ['url'], unique=False)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index('ix_subscription_channel_id')
        batch_op.drop_index('ix_subscription_rss_url')

    op.drop_table('subscription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rss_url', sa.VARCHAR(), nullable=False),
    sa.Column('channel_id', sa.INTEGER(), nullable=False),
    sa.Column('last_checked', sa.DATETIME(), nullable=False),
    sa.Column('rss_title', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rss_url'),
    sa.UniqueConstraint('rss_url', 'channel_id', name='uix_item_rss_url_channel_id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index('ix_subscription_rss_url', ['rss_url'], unique=False)
        batch_op.create_index('ix_subscription_channel_id', ['channel_id'], unique=False)

    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_url'))
        batch_op.drop_index(batch_op.f('ix_feed_channel_id'))

    op.drop_table('feed')
    # ### end Alembic commands ###
